### ISSUE TITLE
Environment set-up

### ISSUE THREAD

**Issue by SparkSign** [SparkSign/zip_walkability#3]
Need to download all of the packages that we will be using for this project. [The packages are listed in step 3 of this article.](https://towardsdatascience.com/making-heat-maps-with-literal-maps-how-to-use-python-to-construct-a-chloropleth-6b65e4e33905)

**Comment by JSchmoney19** [comment]
installed with assistance from samuel- relevant packages installed

**Comment by darrelladrian** [comment]
got it
